apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-http
  template:
    metadata:
      labels:
        app: python-http
        test: test
    spec:
      containers:
        - name: python-http
          image: python:3.11-alpine
          workingDir: /
          command: ["python3", "-m", "http.server", "80"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: python-http-storage
              mountPath: /usr/share/nginx/html/demo
      volumes:
        - name: python-http-config
          configMap:
            name: python-http-config
            defaultMode: 0755
            optional: false
        - name: python-http-storage
          persistentVolumeClaim:
            claimName: python-http-pvc
