apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        test: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          command: ["/bin/sh", "-c", "exec /usr/local/bin/custom-entrypoint.sh"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-storage
              mountPath: /usr/share/nginx/html/demo
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-config
              mountPath: /usr/local/bin/custom-entrypoint.sh
              subPath: custom-entrypoint.sh
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            defaultMode: 0755
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc
