apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-http
  template:
    metadata:
      labels:
        app: python-http
        test: test
    spec:
      containers:
        - name: python-http
          image: python:3.11-alpine
          workingDir: /app
          command: ["python3", "/app/server.py"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: python-http-config
              mountPath: /app
              readOnly: true
            - name: python-http-storage
              mountPath: /usr/share/nginx/html/demo
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 6
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            # timeoutSeconds: 2 # default is 1 second
            # failureThreshold: 3 # default is 3
      volumes:
        - name: python-http-config
          configMap:
            name: python-http-config
            defaultMode: 0755
            optional: false
        - name: python-http-storage
          persistentVolumeClaim:
            claimName: python-http-pvc
