apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  #Default de minikube al parecer
  resources:
    requests:
      storage: 1Gi
