apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: python-http
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - python-http.test.local
    routes:
      - matchers:
          - prefix: /
        routeAction:
          singleDestination:
            upstream:
              name: default-python-http-80
              namespace: gloo-system
