apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  source:
    repoURL: https://storage.googleapis.com/solo-public-helm
    chart: gloo
    targetRevision: 1.19.0
    helm:
      values: |
        gloo:
          gateway:
            enabled: true
        gateway:
          service:
            type: NodePort
        kubeResourceRollout:
          enabled: false
        kubeResourceMigration:
          enabled: false

        gatewayProxies:
          gatewayProxy:
            podTemplate:
              volumes:
                - name: tmp
                  emptyDir: {}
              containers:
                gateway-proxy:
                  volumeMounts:
                    - name: tmp
                      mountPath: /tmp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
